### ISSUE TITLE
use of `get-aws-creds` with environment variables already present fails to renew

### ISSUE THREAD

**Issue by tlelson** [tlelson/tlx#15]
Need to force the call to sts basically anytime this is called and use default profile keys.

**Comment by tlelson** [comment]
Also, a problem when trying to assume another role.

```bash
(general) timbo@MinLen:cashflow-models ❯ get-aws-creds -p Glue -t 528354
ClientError: An error occurred (AccessDenied) when calling the GetSessionToken operation: Cannot call GetSessionToken with session credentials
```

*Soln:* `get-aws-creds` should always use `.aws/credentials file` not env vars. 
_(this could be as simple as just unsetting an env var before subsequent calls)_

**Comment by tlelson** [comment]
Probly shouldn't have commitied that so hastily.  Seems to be a problem assuming a new role over the top of existing session tokens.

To Verify and ensure before promoting to `master`:
- [x] all calls to `get-aws-credentials` get temporaty tokens if an `mfa-serial is present in the config
- [x] subsequent calls to `get-aws-creds` with new profile (try a serivce role) replace existing env vars with new ones.  Of course it will be the users responsibiltity to `export` them

**Comment by tlelson** [comment]
This should work.  Will leave it in dev for a couple of week trialling it before pushing to master.

**Comment by tlelson** [comment]
Been working ok, but passing in mfa token as an argument to a profile doesn't work and boto reprompts

```bash
(general) timbo@MinLen:lambdas ❯ get-aws-creds -p Gluerunner -t 924740
Enter MFA code for arn:aws:iam::571865343317:mfa/tim.elson:
```

**Comment by tlelson** [comment]
looks unlikely that we can fix this without reimplimenting boto's profile scanner since:

```python
In [2]: boto3.session.Session?
Init signature:
boto3.session.Session(
    aws_access_key_id=None,
    aws_secret_access_key=None,
    aws_session_token=None,
    region_name=None,
    botocore_session=None,
    profile_name=None,
)
```

**Comment by divv** [comment]
Nice that this is still in maintenance! Myself and a few others still using it.

I had some weird behaviour with the latest version as well. It would not set credentials _without_ having the env var set previously.
[tlx_stacktrace_20191030.txt](https://github.com/eL0ck/tlx/files/3786854/tlx_stacktrace_20191030.txt)

**Comment by tlelson** [comment]
oh hey @divv !  yea sorry I push to master a bit early on the latest updates and it was a bit hacky.

Rather than using the bash fuction `gac` i've taken to writing the creds in `/tmp/` and sourcing them.  That way any new terminal session gets the temp tokens.

```bash
get-aws-creds --quiet > /tmp/awscreds
```

I still use `gac` to blast locals though if i want to assume a different role to test IAM policies
